### ISSUE TITLE
U have stopped working on this device ?

### ISSUE THREAD

**Issue by ghost** [MediatekAndroidDevelopers/android_device_elephone_vowney_lite#2]

**Comment by ghost** [comment]
There is official leeco le1s marshmallow kernel available.. which has mt6795 mtk processor (opensource.le.com)
 Here is the clone :  https://github.com/vishalk17/rebase-2/tree/stock

**Comment by dragonpt** [comment]
Yeah, and ?
Not getting what has that to do with this device?

We have our own repositories for all kind of mediatek devices bring-up

**Comment by dragonpt** [comment]
The development for this device has stopped 

* device is pretty much dead
* elephone sucks
* elephone sucks ( again)
* old & deprecated & no one cares about it
* no community
* elephone sucks

**Comment by ghost** [comment]
Actually Sir, I thought as my le1s and this device has same kind of processor. #mt6795 #3.10.xx
So, Kernel source would be helpful if this device is in development.  thats why I had created
issued to know the status of the development for this device.

I am trying to develop oreo compatible rom (los15) from months. But everytime it fails to bootup not even got bootanimation. I m not able to determine root cause of bootup issue..
